environment:
  matrix:
  - nodejs_version: "5.0"
  - nodejs_version: "6.0"

artifacts:
  C:\Users\appveyor\AppData\Local\Temp\1\angular-cli-**\*

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test
  - npm run test:e2e

build: off
