sudo: false
env:
  - NODE_VERSION=4
  - NODE_VERSION=5

os:
  - linux
  - osx
script: npm run-script test
before_install:
  - source build_scripts/osx-before_install.sh
  - nvm install $NODE_VERSION
  - npm config set spin false
install:
  - node --version
  - npm --version
  - git --version
  - npm install --no-optional
