name: Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize environment
        uses: angular/dev-infra/github-actions/npm/checkout-and-setup-node@c88496832e686b534021a01659a239a9e0976af0
      - name: Check Package Licenses
        uses: josephperrott/dev-infra/github-actions/linting/licenses@25d799e11b46ce36195d43aaf392def64b1c83fb
        with:
          allow-dependencies-licenses: 'pkg:npm/thingies@1.21.0'
      